### ISSUE TITLE
建议添加对 editormd 的设置功能

### ISSUE THREAD

**Issue by EINDEX** [chen2aaron/django-editormd#4]
这个编辑器有一些很厉害的功能，希望可以添加一个配置功能，像这个 [django-ckeditor](https://github.com/django-ckeditor/django-ckeditor) 添加一个设置项，实现在 settings 里复写 `EDITORMD_CONFIG` 属性来选择功能。

**Comment by chen2aaron** [comment]
嗯嗯 我也考虑过，等抽空就去弄！
